{% set name = "doubt" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/doubt-{{ version }}.tar.gz
  sha256: 864eebe825bb2000c4a8297102c2fec07541963784efb4b3d337be7a616a462b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - poetry
    - pip
  run:
    - python >=3.8,<3.11
    - tqdm >=4.62.0,<5.0.0
    - numpy >=1.23.0,<2.0.0
    - pandas >=1.4.0,<2.0.0
    - joblib >=1.2.0,<2.0.0
    - scikit-learn >=1.1.0,<1.3.0
    - pytables >=3.7.0,<4.0.0
    - xlrd >=2.0.1,<3.0.0
    - openpyxl >=3.0.10,<4.0.0
    - pytables >=3.7.0,<3.8.0

test:
  imports:
    - doubt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saattrupdan/doubt
  summary: Bringing back uncertainty to machine learning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
